// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  image: string;
  layaut: string;
  root: string;
  sabTitle: string;
  text: string;
}
export const cssExports: CssExports;
export default cssExports;
